apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myapi-deployment
spec:
  selector:
    matchLabels:
      app: myapi
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: hello-fargate:2.1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapi-service
  labels:
    app: myapi
spec:
  type: NodePort
  ports:
  - name: myapi
    port: 80
    targetPort: 80
  selector:
    app: myapi
