---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: managed-cluster
  region: ap-southeast-2

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 5
    desiredCapacity: 1
    labels: {role: worker}
    tags:
      nodegroup-role: worker
