---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-managed-cluster
  region: ap-southeast-2

managedNodeGroups:
  - name: managed-ng-0
    minSize: 1
    maxSize: 10
    desiredCapacity: 1
    labels:
      role: worker
      app: myapi
    tags:
      nodegroup-role: worker
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/my-managed-cluster: owned
      k8s.io/cluster-autoscaler/node-template/label/app: myapi

