apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myapi-deployment
spec:
  selector:
    matchLabels:
      app: myapi
  replicas: 1
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: 979037402244.dkr.ecr.us-west-2.amazonaws.com/joshpeak/does-it-scale:5.0.0
        ports:
        - containerPort: 80
        resources:
            requests:
              memory: "64Mi"
              cpu: "0.5"
            limits:
              memory: "256Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: myapi-service
  labels:
    app: myapi
spec:
  type: NodePort
  ports:
  - name: myapi
    port: 80
    targetPort: 80
  selector:
    app: myapi
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: api-backend
spec:
  prefix: /
  service: myapi-service
  timeout_ms: 0
  idle_timeout_ms: 0
  connect_timeout_ms: 120000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler #this requires https://github.com/kubernetes-sigs/metrics-server
metadata:
 labels:
   app: myapi
 name: myapi-autoscaler
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: myapi-deployment
 minReplicas: 1
 maxReplicas: 100
 targetCPUUtilizationPercentage: 50
